# Generated by Django 4.1.1 on 2022-11-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seuapp', '0003_produtos_pedidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='is_fav',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
